title: BehindTheBathroomStalls
email: andrewmgrube@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://behindthebathroomstalls.com" # the base hostname & protocol for your site, e.g. http://example.com

# Author settings
author: Andrew Grube # add your name
author-pic: andrew-face.jpg
about-author: My name is Andrew Grube. I’m a Cloud Engineer working in downtown Kansas City, Missouri. I also run this blog!

# Contact links
email: andrewmgrube@gmail.com
website: andrewgrube.com
linkedin: andrew-grube-74124821/
github: ThrownJupiter
twitter: '@ThrownJupiter'
instagram: ThrownJupiter

# Newsletter
mailchimp: # Add your MailChimp form identifier.

# Disqus
disus_identifier: xandr00 # Add your discus identifier

# Tracker
analytics: UA-109078200-1 # Google Analytics

# Paginate
paginate: 6
paginate_path: /page:num/

# Build settings
markdown: kramdown

plugins:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-sitemap
include: [_pages]
exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock", "package-lock.json", "assets/css/sass/"]
